services:
  db:
    image: postgres:16.1
    restart: always
    container_name: integration-tests-prisma
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
