services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql
volumes:
  postgres:
