---

- name: Create the SSH public key file
  copy: content="{{ git_ssh_pub_key }}"
        dest="/root/.ssh/{{ project_name }}.pub"
        mode=0644

- name: Create the SSH private key file
  copy: content="{{ git_ssh_priv_key }}"
        dest="/root/.ssh/{{ project_name }}"
        mode=0600

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version="{{ git_branch }}"
       dest={{ project_path }}
       accept_hostkey=yes
       key_file="/root/.ssh/{{ project_name }}"
  when: setup_git_repo is defined and setup_git_repo
  tags: git

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git