
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.ssh.forward_agent = true
  config.vm.synced_folder ".", "/vagrant", type:"virtualbox"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "%(project_name)s/orchestration/vagrant.yml"
    ansible.host_key_checking = false
    ansible.verbose = "v"
  end
end
